### ISSUE TITLE
Please keep the Interface + Exception suffixes

### ISSUE THREAD

**Issue by nicolas-grekas** [flysystemphp/filesystem#1]
When I navigate e.g. Doctrine's codebase, I'm always wasting time wondering if this symbol is a class or an interface. Removing the suffixes makes things harder to work with.

I don't always work with phpstorm btw, that's maybe why. But code shouldn't require advanced IDEs to be workable.

Check https://discourse.zendframework.com/t/interface-suffix-take-it-or-leave-it/259 for previous discussion on the topic, I'm not alone thinking this way.

Thanks for considering :)

**Comment by frankdejonge** [comment]
Although I understand that people have opinions about this, I personally feel very strongly about showing an alternative method. The interfaces and exceptions in Flysystem are unmistakably interfaces and exceptions. In my opinion the suffixes are redundant information (which is not bad) that steer people away from good naming (which _is_ bad).

For discoverability the exceptions all have a clear name, for all the main operations they are prefixed with `UnableTo-` for discoverability. The interfaces imo leave very little room for thinking they are concretes:

- FilesystemAdapter
- FilesystemReader
- FilesystemWriter
- etc

Thank you for bringing it up. I hope you understand my decision not to conform to this naming scheme. If not, I hope you respect my decision either way.

**Comment by nicolas-grekas** [comment]
Totally fine :)
